### ISSUE TITLE
[REQUIREMENT] Fines Page

### ISSUE THREAD

**Issue by sai-k02** [sai-k02/library-management-system#10]
- fine_amt attribute is a dollar amount (two decimal places)
- paid attribute i.e boolean
- Fines rate => 0.25/day
- Provide a refresh button
- There are two scenarios for late books
1. Late books that have been returned — the fine will be [(the difference in days between the due_date and date_in) * $0.25].
2. Late books that are still out the estimated fine will be [(the difference between the due_date and TODAY) * $0.25].
- If a row already exists in FINES for a particular late BOOK_LOANS record, then
- If paid == FALSE, do not create a new row, only update the fine_amt if different than
current value.
- If paid == TRUE, do nothing.
• Provide a mechanism for librarians to enter payment of fines (i.e. to update a FINES record where paid == TRUE)
- Do not allow payment of a fine for books that are not yet returned.
- Display of Fines should be grouped by card_no. i.e. SUM the fine_amt for each
Borrower.
- Display of Fines should provide a mechanism to filter out previously paid fines (either
by default or choice).

**Comment by MertBuyulu** [comment]
I will be handling the backend logic for this page

**Comment by MertBuyulu** [comment]
Done!!
