### ISSUE TITLE
[REQUIREMENT] Book Loans Page

### ISSUE THREAD

**Issue by sai-k02** [sai-k02/library-management-system#8]
Using your GUI, be able to check in a book. For examle, be able to locate BOOK_LOANS tuples by searching on any of BOOKS.book_id, BORROWER.card_no, and/or any substring of BORROWER name. Once located, provide a way of selecting one of potentially multiple results and a button (or menu item) to check in (i.e. today as the date_in in corresponding BOOK_LOANS tuple).

**Comment by MertBuyulu** [comment]
Done
