### ISSUE TITLE
[REQUIREMENT] Borrowers Page

### ISSUE THREAD

**Issue by sai-k02** [sai-k02/library-management-system#9]
Using your GUI, be able to create new borrowers in the system.
• All name, SSN, and address attributes are required to create a new account (i.e. value
must be not null).
• You must devise a way to automatically generate new card_no primary keys for each new
tuple that uses a compatible format with the existing borrower IDs.
• Borrowers are allowed to possess exactly one library card. If a new borrower is attem

**Comment by MertBuyulu** [comment]
The logic is ready, once the server implements the functionality of generating a unique borrower ID, the requirement can be put to a test.

**Comment by MertBuyulu** [comment]
Done!
